# -*- coding: utf-8 -*-
"""FRA2020 - Foodentical

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ah26wmJiL-37ZdDbxxG9AurqCF4A6uiM
"""

import numpy as np
import pandas as pd
import math
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import sigmoid_kernel

food = pd.read_csv("/content/FRA2020_duatiga_Indonesia - Calculation.csv")

food.head()

food.shape

food.info()

food_tfidf = TfidfVectorizer(analyzer='word',
                      ngram_range=(1, 2),
                      min_df=0.003,
                      max_df=0.5,
                      max_features=None,
                      stop_words= 'english')

food['foodDesc'] = food['foodDesc'].fillna('')

food_matrix = food_tfidf.fit_transform(food['foodDesc'])
food_matrix

cosine_similarities = cosine_similarity(food_matrix, food_matrix)

indices = pd.Series(food.index, index=food['foodName'], dtype = object).drop_duplicates()

indices

def recommend(foodName, cos = cosine_similarities):
    idx = indices[foodName]
    food_score = pd.Series(cos[idx]).sort_values(ascending = False)
    food_top5 = list(food_score.iloc[1:6].index)
    
    return food['foodName'].iloc[food_top5]

recommend('Sate ')